### ISSUE TITLE
App crashes on creating map

### ISSUE THREAD

**Issue by Evanzsnr** [capacitor-community/google-maps#114]
**Describe the bug**
I installed this plugin, updated the specific files as described and built the app. The build was successful but the app crashes at the point of creating the map. I checked the api key and it is okay since it works well when I use it elsewhere. This is the crash log

```
java.lang.NullPointerException: Attempt to invoke virtual method 'double java.lang.Double.doubleValue()' on a null object 
reference	at com.hemangkumar.capacitorgooglemaps.CapacitorGoogleMaps$1.run(CapacitorGoogleMaps.java:135)	at 
android.os.Handler.handleCallback(Handler.java:790)	at android.os.Handler.dispatchMessage(Handler.java:99)	at 
android.os.Looper.loop(Looper.java:164)	at android.app.ActivityThread.main(ActivityThread.java:6543)	at 
java.lang.reflect.Method.invoke(Native Method)	at 
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)	at 
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:810)

```

**To Reproduce**
1. Install the plugin
2. Build the app
3. Run the app

**Expected behavior**
The map should display when the app is run.

**Comment by tolutronics** [comment]
Somehow, the latitude and longitude parameters that where suppossedly optional in the CapacitorGoogleMaps.create were causing the error when not provided, so you need to provide those fields

const boundingRect = this.yourMapView.nativeElement.getBoundingClientRect() as DOMRect;
 CapacitorGoogleMaps.create({
      width: Math.round(boundingRect.width),
      height: Math.round(boundingRect.height),
      x: Math.round(boundingRect.x),
      y: Math.round(boundingRect.y),
      zoom: 5,
      latitude:xxxxxxxxx,    // you can get the location and add the latitude
      longitude:xxxxxxx.   // you can get the location and add the longitude
    });

**Comment by tolutronics** [comment]
if you face any other issue let me know

**Comment by tolutronics** [comment]
ok, i will look into it

**Comment by tafelnl** [comment]
We've just released a (pretty stable) beta for version 2 of this plugin under the name [`@capacitor-community/google-maps`](https://www.npmjs.com/package/@capacitor-community/google-maps).

It features a more complete and consistent API. Also the map can finally be rendered behind the webview in this new version.

Extensive documentation for v2 can be found here: https://capacitor-community.github.io/google-maps/

Since version 1 lacked a lot of (basic) features, did not have good coding practices, had a poor API and it is not recommended to use it anymore, we've dropped support for it. Therefore I will close this issue. We believe version 2 offers a better Developer Experience and is a much better fit for anyones use case.
