### ISSUE TITLE
[Question] How can i get a marker id's ?

### ISSUE THREAD

**Issue by GEnAdInE** [capacitor-community/google-maps#123]
Hi ,

I'm looking to know how to retreive the id of a marker to delete it ? how can i do ? 

Thanks,
Robin ^^

**Comment by tafelnl** [comment]
We've just released a (pretty stable) beta for version 2 of this plugin under the name [`@capacitor-community/google-maps`](https://www.npmjs.com/package/@capacitor-community/google-maps).

It features a more complete and consistent API. Also the map can finally be rendered behind the webview in this new version.

Extensive documentation for v2 can be found here: https://capacitor-community.github.io/google-maps/

Since version 1 lacked a lot of (basic) features, did not have good coding practices, had a poor API and it is not recommended to use it anymore, we've dropped support for it. Therefore I will close this issue. We believe version 2 offers a better Developer Experience and is a much better fit for anyones use case.

**Comment by mujie-dm** [comment]
> Hi ,
> 
> I'm looking to know how to retreive the id of a marker to delete it ? how can i do ?
> 
> Thanks, Robin ^^

> 

```
     const mymarker = await CapacitorGoogleMaps.addMarker({
       mapId: element.getAttribute("data-maps-id"),
       position: {
         latitude: position[0],
         longitude: position[1],
       }, 
       preferences: {
         title: 'My Mark',
         snippet: 'My Location',
       }
     });

    //Get the ID's
    console.log(JSON.parse(JSON.stringify(mymarker))['marker']['markerId']);
```
 
 Regards,
 Mujie
