### ISSUE TITLE
Missing definitons in definitions.ts for setCamera

### ISSUE THREAD

**Issue by hemangsk** [capacitor-community/google-maps#35]

**Comment by hemangsk** [comment]
- [ ] Ensure the setCamera allows individual properties to be set, and properties whose values were not passed to the parameters are set to the existing value.
- [ ] Create moveCamera, move out the animate bits from setCamera to moveCamera

**Comment by tafelnl** [comment]
We've just released a (pretty stable) beta for version 2 of this plugin under the name [`@capacitor-community/google-maps`](https://www.npmjs.com/package/@capacitor-community/google-maps).

It features a more complete and consistent API. Also the map can finally be rendered behind the webview in this new version.

Extensive documentation for v2 can be found here: https://capacitor-community.github.io/google-maps/

Since version 1 lacked a lot of (basic) features, did not have good coding practices, had a poor API and it is not recommended to use it anymore, we've dropped support for it. Therefore I will close this issue. We believe version 2 offers a better Developer Experience and is a much better fit for anyones use case.
