### ISSUE TITLE
Fix default config setup in setCamera

### ISSUE THREAD

**Issue by hemangsk** [capacitor-community/google-maps#40]
Reported by @gbrits 

Ref https://github.com/hemangsk/capacitor-googlemaps-native/pull/39/files#diff-c1fd3aab06a21d07732bdebb118e40a701c8f6316740ba02d6ad913cc956c5beL474 

googleMap.getCameraPosition() causes app to crash. We need to find a proper way to get current camera position and use that config as the fallback value in setCamera.

**Comment by tafelnl** [comment]
We've just released a (pretty stable) beta for version 2 of this plugin under the name [`@capacitor-community/google-maps`](https://www.npmjs.com/package/@capacitor-community/google-maps).

It features a more complete and consistent API. Also the map can finally be rendered behind the webview in this new version.

Extensive documentation for v2 can be found here: https://capacitor-community.github.io/google-maps/

Since version 1 lacked a lot of (basic) features, did not have good coding practices, had a poor API and it is not recommended to use it anymore, we've dropped support for it. Therefore I will close this issue. We believe version 2 offers a better Developer Experience and is a much better fit for anyones use case.
