### ISSUE TITLE
Marker icon not changing

### ISSUE THREAD

**Issue by ChiKaLiO** [capacitor-community/google-maps#44]
*Edit*: Plateform Android
Here i my code:

```
CapacitorGoogleMaps.addMarker({
        latitude: coordinates.coords.latitude,
        longitude: coordinates.coords.longitude,
        title: "My Location",
        snippet: "Custom Snippet",
        isFlat: true,
        url: "../../assets/images/blue-logo.png"
      });
```

**Comment by hemangsk** [comment]
Hi! Does it show any exceptions being thrown, in the android studio logcat?

**Comment by ChiKaLiO** [comment]
Hello, sorry for late reply.. no nothing red marker does appear, and following the code i think it's not yet implemented

**Comment by stevebrowndotco** [comment]
I confirm this bug. I cannot use a custom marker icon.

**Comment by tafelnl** [comment]
@ChiKaLiO To point you in the right direction, in this package they implemented it already. You could specifically take a look at [`setIcon`](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/bdb7af4730857a6b51662a8cfd180f6c5a3dce35/src/android/plugin/google/maps/PluginMarker.java#L1016). It is important that the icon will be set in combination with the use of a `AsyncTask` on Android. In that package they extended the class to [`AsyncLoadImage`](https://github.com/mapsplugin/cordova-plugin-googlemaps/blob/bdb7af4730857a6b51662a8cfd180f6c5a3dce35/src/android/plugin/google/maps/AsyncLoadImage.java). For iOS you could also take a look at that package, to see how they've done it there.

**Comment by andreasaphilo** [comment]
Did they implement the custom marker at this point? Is there any hacky way to just replace the original red marker icon with mine?

**Comment by va2ron1** [comment]
This is the issue... In the definitions of the addMarker the parameter is called [url](https://github.com/capacitor-community/capacitor-googlemaps-native/blob/d016dbea3341ddeefc5333a0b9a4a17597c0c3d0/src/definitions.ts#L32), but the implementation in iOS is called [iconUrl](https://github.com/capacitor-community/capacitor-googlemaps-native/blob/d016dbea3341ddeefc5333a0b9a4a17597c0c3d0/ios/Plugin/Plugin.swift#L68)

A [pull request](https://github.com/capacitor-community/capacitor-googlemaps-native/pull/126) has been added renaming the parameter

**Comment by tafelnl** [comment]
We've just released a (pretty stable) beta for version 2 of this plugin under the name [`@capacitor-community/google-maps`](https://www.npmjs.com/package/@capacitor-community/google-maps).

It features a more complete and consistent API. Also the map can finally be rendered behind the webview in this new version.

It also adds better support for custom marker icons for the iOS platform. Android is still WIP and PRs are welcome. 

Extensive documentation for v2 can be found here: https://capacitor-community.github.io/google-maps/

Since version 1 lacked a lot of (basic) features, did not have good coding practices, had a poor API and it is not recommended to use it anymore, we've dropped support for it. Therefore I will close this issue. We believe version 2 offers a better Developer Experience and is a much better fit for anyones use case.
