### ISSUE TITLE
dragEnded event does not fire

### ISSUE THREAD

**Issue by stevebrowndotco** [capacitor-community/google-maps#88]
**Describe the bug**
The dragEnded event does not fire

**To Reproduce**

I add the following code:
```typescript
    CapacitorGoogleMaps.addListener("dragEnded", async (mapEvent) => {
       // do something
    });
```

**Expected behavior**
When I drag my finger over the map and release it from the screen, I expect the callback in the second parameter of "addListener" to fire. 

**Actual behavior**
Nothing happens...

By the way, if I change to "didChange" this indeed does fire, but I don't want that particular event as it is too noisy.

Only tested on a real iOS device right now...
Thank you!

**Comment by timsar2** [comment]
Any news?

**Comment by va2ron1** [comment]
If anyone still having this issue, a solution is at my fork https://github.com/capacitor-community/capacitor-googlemaps-native/pull/127

**Comment by tafelnl** [comment]
We've just released a (pretty stable) beta for version 2 of this plugin under the name [`@capacitor-community/google-maps`](https://www.npmjs.com/package/@capacitor-community/google-maps).

It features a more complete and consistent API. Also the map can finally be rendered behind the webview in this new version.

Extensive documentation for v2 can be found here: https://capacitor-community.github.io/google-maps/

Since version 1 lacked a lot of (basic) features, did not have good coding practices, had a poor API and it is not recommended to use it anymore, we've dropped support for it. Therefore I will close this issue. We believe version 2 offers a better Developer Experience and is a much better fit for anyones use case.
